### PR TITLE
recursive solution for fizzbuzz

### PR DESCRIPTION
**Pull request by hanstf**
yoo maybe it helps, can you suggest any pros for it ?

### CODE REVIEW

**Review by jreina — CHANGES_REQUESTED** [review]
It looks like I have already merged in a recursive.js.

Can you please rename your file to recursive.es6 and recursive.es6.md?

**Comment by jreina** [comment]
Pros: Uses const instead of var 😁

**Comment by hanstf** [comment]
alright modified

**Review by jreina — APPROVED** [review]

**Comment by jreina** [comment]
Perfect! Congrats on your first PR and thank you for your contribution.

**Pull request merged**
